# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  enable-experiment:
    - native-assets