name: enet
description: "A new Flutter FFI plugin project."
version: 0.0.1

environment:
  sdk: ^3.5.3

dependencies:
  ffi: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
