name: enet
description: "A new Flutter FFI plugin project."
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  ffi: ^2.1.3
  logging: ^1.3.0
  native_assets_cli: ^0.9.0
  native_toolchain_c: ^0.6.0
 
dev_dependencies:
  test: ^1.25.8