name: enet
description: >-
  ENet Dart reliable, low-latency UDP networking 
  for Flutter and Dart applications.
repository: https://github.com/Nika0000/enet
version: 0.0.1

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.5.4

dependencies:
  ffi: ^2.1.3
  native_assets_cli: ^0.11.0
  native_toolchain_c: ^0.8.0 
 
dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ">=6.0.0 <10.0.0"

topics:
  - udp
  - enet
  - enet-dart